- tools/p11ne-cli
The nitro-cli-config is the old naming of the allocator script and is thus misleading for users.
> p11ne-cli: fix naming for nitro-enclaves-allocator

- src/vtok_agent/src/agent/mngtok.rs
- src/vtok_agent/src/agent/mod.rs
- src/vtok_agent/src/config.rs
- src/vtok_agent/src/enclave.rs
- src/vtok_agent/src/main.rs
- src/vtok_agent/src/util.rs
- src/vtok_rpc/src/transport.rs
- src/vtok_srv/src/worker.rs
- src/vtok_tool/src/main.rs
- Changed default token refresh interval to 12h;
- Reload nginx after token refresh;
- Added the mechanism to retry all RPCs that involve attestation
- Added a new config option under enclave.attestation_retry_count,
allowing the user to set the number of retries;
- Changed the P11Enclave interface to expose specific RPC methods
instead of the generic `P11Enclave::rpc`;
- Fixed an issue whereby the RPC Transport trait would needlessly require
ownership of schema::ApiRequest and schema::ApiResponse objects.
Transport methods now borrow these objects.
> nginx: reload after token refresh

- env/enclave/Dockerfile
- env/parent/Dockerfile
- env/parent/setup.sh
- tools/devtool
Switched from building nitro-cli from source to using the AL2 RPM, and
added a couple of fixes:
- build as root;
- removed GITHUB_CREDS;
- cache cargo registry under build/, so it doesn't get recreated with
each cargo build.
Signed-off-by: Dan Horobeanu <dhr@amazon.com>
> build: nitro-cli as rpm & co

- src/vtok_agent/src/util.rs
- tools/devtool
- Added support to use different Rust toolchains for parent-side bins vs
enclave-side bins;
- Set parent-side Rust to 1.38.
Signed-off-by: Dan Horobeanu <dhr@amazon.com>
> build: rust toolchain split

- env/enclave/Dockerfile
- env/parent/Dockerfile
Due to a known docker issue, the build hangs when adding
an user with large UID during build.
As a workaround use useradd with the -l option.
> Fix build issues with large UIDs

- tools/p11ne-cli
Currently the commands made available by the
p11ne-cli report their output as JSON, by
piping their output through plain `jq`.
This was found to introduce a problem when trying
to process the output in shell scripts (e.g. storing
the output in a shell variable for further processing).
Plain `jq` expects the destination of the JSON
representation to be a terminal.
This commit adds a pretty-print filter to `jq`
(`jq '.'`) such that the output can be processed in
shell scripts as well.
Signed-off-by: Gabriel Bercaru <bercarug@amazon.com>
> p11ne-cli: improve JSON output reporting

- run-nitro-enclaves-acm-tests
Removed the service stop/restart header/footer for
each test, since all tests can make use of the same
p11ne enclave without the need for `p11ne-cli` creating
a new one every time.
Signed-off-by: Gabriel Bercaru <bercarug@amazon.com>
> testing: update smoketests script

- tools/p11ne-cli
The p11ne-cli previously used only 'us-east-1' as its target region,
which made it behave incorrectly on all other regions. This change
makes the CLI use the region of the instance it's running on, based
on the vsock-proxy's endpoint configuration.
Signed-off-by: Andrei Trandafir <aatrand@amazon.com>
*Issue #, if available:*
> tools: Fix p11ne-cli selection of AWS region

- tools/p11ne-cli
IMDSv2 uses session-oriented requests. This is
why we have to generate a session token, and
use it in subsequent requests.
Signed-off-by: Bogdan Vasile <bve@amazon.com>
Executed the `ensure_aws_creds` function in isolation and checked that the IMDSv2 session token is fetched, and that the AWS role credentials are retrieved.
> Support IMDSv2 in the p11ne-cli tool.

- tools/p11ne-cli
Curl prints a lot of output to stderr when executing,
even if it ends ok.
Redirect the stderr to log.err file and print it only
if the command fails.
Signed-off-by: popegeo <popegeo@amazon.com>
*Issue #, if available:*
> Print curl output to stderr only if it fails

- src/vtok_p11/src/crypto/mod.rs
Some aarch64 platforms complain about char vs unsigned char
types. Make this an inferred cast to unlock aarch64 builds.
--> src/vtok_p11/src/crypto/mod.rs:274:47
|
274 |   ... { ffi::BN_bn2bin(bn, ret.as_mut_ptr() as \
*mut i8) };
|       ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
|
= note: expected raw pointer `*mut u8`
found raw pointer `*mut i8`
> p11/crypto: fix aarch64 build

- docs/java_keystore.md
Document some steps on how to get a working Java PKCS11 keystore using a provisioned pkcs#11 token.
> docs: provide a Java PKCS11 Keystore example

- env/enclave/Dockerfile
Was a hard dependency in the original release
for building the aws crypto library.
> env: remove unused quilt package

- src/vtok_agent/service/acm.example.yaml
Document the configurable parameters from the example yaml file and also provide an example on how to configure a second
token (i.e. for another domain).
> docs: document the config parameters inline

- src/vtok_agent/src/agent/mod.rs
So far, we issued multiple signals to Nginx in succession when DEFAULT_TOKEN_REFRESH_INTERVAL_SECS elapsed to potentially reload the certificate:
1) SIGUSR2 - Upgrade nginx executable on the fly
2) SIGWINCH - Shut down gracefully worker processes
3) SIGQUIT - Shut down gracefully
That meant every time, we eventually shut down the full Nginx server which then may or may not get restarted by systemd.
All of the above is unnecessary. We merely need to tell Nginx that a new configuration arrived through the SIGHUB signal at which point it will wind down any active worker and start new ones with the new configuration, including new certificate.
So let's switch to a single SIGHUB signal instead.
> agent: Don't restart Nginx, only reload

- Cargo.lock
- README.md
- env/enclave/Dockerfile
- src/vtok_agent/Cargo.toml
- src/vtok_p11/Cargo.toml
- src/vtok_p11/src/crypto/ffi.rs
- src/vtok_srv/Cargo.toml
- tools/devtool
* Update dependencies raised by dependabot
* Update AWS dependencies: `aws-lc`, `ne-sdk`, `nsm-lib`, etc.
* Update Rust version to 1.63
Testing was done with https://github.com/aws/aws-nitro-enclaves-acm/blob/main/tests/testtool.
Results:
```
$ ./tests/testtool openssl --kms-key-id ****** --kms-region ******
Running Sign&verify tests
Running RSA-PSS Sign&Verify tests using openssl
test_openssl_digestsignverify_rsapss_rsa1024_0B_0_sha1
test_openssl_digestsignverify_rsapss_rsa1024_0B_0_sha1 ............... PASSED
...
test_x509_noroot_chain ............................................... PASSED
test_x509_invalid_chain
test_x509_invalid_chain .............................................. PASSED
744 tests passed, 0 tests failed
```
By submitting this pull request, I …
> Upgrade of dependencies

- src/vtok_agent/src/imds.rs
*Issue #, if available:* #15, #55, #129
In VPCs without a NAT Gateway, the current code will fail to resolve IAM instance roles that have a `Path` a because the Path is not returned from the IMDS. This code will look for a specific EC2 Instance Role tag (`InstanceRoleArn`) that will be used instead of calling `iam:GetRole` (which will fail in VPCs without NAT Gateways).
The risk of someone defining another IAM role and being able to download the private certificate should be mitigated by the fact that [AssociateEnclaveCertificateIamRole](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateEnclaveCertificateIamRole.html) wouldn't have been called allowing the IAM role to download the certificate from the S3 bucket.
`sts:GetCallerIdentity` also …
> [feat] Support retrieving instance role ARN from an EC2 instance tag

- tests/testtool
- tools/p11ne-db
Some of the test and helper scripts don't work on AL2023 because of newer versions of `aws cli` and `openssl`.
Necessary fixes:
* p11ne-db: use explicit raw-in-base64-out binary input format
* testtool: adjust testtool for al2023
> AL2023 test and helper script fixes

- src/vtok_agent/src/agent/mngtok.rs
- src/vtok_agent/src/agent/mod.rs
- src/vtok_agent/src/util.rs
To ensure consistent state, **nginx** should be restarted instead of just reloading its configuration when the **nitro-enclaves-acm** service is restarted.
> restart nginx when nitro-enclaves-acm is restarted

- tools/devtool
This commit mounts the cargo registry under the build/ folder, which prevents the registry from being recreated for each build. By caching the registry, subsequent builds will be faster as cargo won't need to download dependencies from scratch.
> Speed up builds for the token provider library

- src/vtok_agent/service/acm-httpd.example.yaml
- src/vtok_agent/service/acm.example.yaml
- src/vtok_agent/src/agent/mngtok.rs
- src/vtok_agent/src/agent/mod.rs
- src/vtok_agent/src/config.rs
- tools/README.md
- tools/s3-db
These changes add a new token source, which allows users to store and retrieve self-signed certificates from regular S3 buckets for testing purposes.
> Introduce the S3 source type for tokens

- src/vtok_agent/src/agent/mngtok.rs
- src/vtok_agent/src/agent/mod.rs
- src/vtok_agent/src/util.rs
- src/vtok_common/src/config.rs
- src/vtok_p11/src/api/mod.rs
- src/vtok_p11/src/backend/device.rs
- src/vtok_p11/src/backend/slot.rs
- src/vtok_p11/src/backend/token.rs
Refreshing tokens through webserver reloads can lead to performance bottlenecks and other issues. This new approach aims to move the refresh logic into the enclave, enabling more efficient and optimized token refreshing.
> Implement an internal renewal mechanism for token refresh operations

- src/vtok_agent/src/agent/mod.rs
- src/vtok_agent/src/main.rs
- src/vtok_agent/src/util.rs
```
agent: Populate systemd config override when restarting
On AL2 there is a known bug which prevents httpd from working correctly
with PKCS#11 when it is started with -DFOREGROUND option. This option is
set by default in the sample systemd service which gets installed
alongside httpd.
In order to mitigate this problem, override the config explicitly in the
agent code: it was done in this way before until the commit
"c35f99b vtok_agent: Decouple webserver reload from agent" accidentally
removed the httpd systemd configuration code.
So, introduce a function which allows dynamic reconfiguration of the
web-server systemd service when executing post-sync actions. Define the
config for HTTPD (there is already a const string with the required
config in the code).
Since we need to reload the …
```
> agent: Populate systemd config override when restarting

- env/enclave/Dockerfile
- tools/devtool
Currently, the project can't be build with rustc 1.63 due to the fact that some of the dependencies of aws-nitro-enclaves-nsm-api rely on the newer compiler versions. It generates the following errors:
error: package `once_cell v1.21.3` cannot be built because it requires rustc 1.65 or newer, while the currently active rustc version is 1.63.0
error: package `serde_bytes v0.11.17` cannot be built because it requires rustc 1.68 or newer, while the currently active rustc version is 1.63.0
Bump the version to 1.71, as specified in the aws-nitro-enclaves-nsm-api Config.toml to be able to build this subproject.
Also, since public docker hub has a pull rate limit, use public AWS ECR in order to avoid build failures if there were too many build attempts.
By submitting this pull request, I confirm …
> Fix build process

- cdk/src/assets/user-data-scripts/AL2023/nginx-conf.sh
As pointed out by @jplock , the latest AL2023 2023.7 release made changes to the `/etc/pki/tls/openssl.cnf` file that broke the line at https://github.com/aws/aws-nitro-enclaves-acm/blob/main/cdk/src/assets/user-data-scripts/AL2023/nginx-conf.sh#L19
Instead of modifying the `openssl.cnf` file directly, this change creates a new file `/etc/pki/tls/openssl.d/openssl-acm.cnf` which is included in the main `openssl.cnf` file. The new `openssl-acm.cnf` file contains the necessary configuration for the ACM use case.
This more generic solution should be robust against future changes to `openssl.cnf`, as the ACM-specific configuration is isolated in a separate file.
*Testing done:*
I have tested the changes on a new AL2023 instance with NGINX and confirmed that the ACM …
> cdk: Fix nginx-conf.sh configuration for AL2023 2023.7 release
